"""added relationships

Revision ID: 6eb75e268378
Revises: c10d8eabe637
Create Date: 2023-08-10 09:35:01.549950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb75e268378'
down_revision = 'c10d8eabe637'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freebies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dev_id', sa.String(), nullable=True))
        batch_op.drop_constraint('fk_freebies_company_companies', type_='foreignkey')
        batch_op.drop_constraint('fk_freebies_dev_devs', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_freebies_dev_id_devs'), 'devs', ['dev_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_freebies_company_id_companies'), 'companies', ['company_id'], ['id'])
        batch_op.drop_column('dev')
        batch_op.drop_column('company')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freebies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('dev', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_freebies_company_id_companies'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_freebies_dev_id_devs'), type_='foreignkey')
        batch_op.create_foreign_key('fk_freebies_dev_devs', 'devs', ['dev'], ['id'])
        batch_op.create_foreign_key('fk_freebies_company_companies', 'companies', ['company'], ['id'])
        batch_op.drop_column('dev_id')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
