"""created freebies table

Revision ID: c10d8eabe637
Revises: 5f72c58bf48c
Create Date: 2023-08-10 09:29:38.864666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10d8eabe637'
down_revision = '5f72c58bf48c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freebies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('dev', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company'], ['companies.id'], name=op.f('fk_freebies_company_companies')),
    sa.ForeignKeyConstraint(['dev'], ['devs.id'], name=op.f('fk_freebies_dev_devs')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('freebies')
    # ### end Alembic commands ###
