"""added realationship between dev and company thru association proxy

Revision ID: c6055ee44228
Revises: ca112fc8fd60
Create Date: 2023-08-10 10:38:27.576409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6055ee44228'
down_revision = 'ca112fc8fd60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
