"""modified freebie column values

Revision ID: ca112fc8fd60
Revises: 6eb75e268378
Create Date: 2023-08-10 10:11:00.251489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca112fc8fd60'
down_revision = '6eb75e268378'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
